FROM ncbi/sra-tools:3.0.0
RUN apk --no-cache update \
 && apk --no-cache add python3 py3-pip py3-cffi py3-cryptography \
 && pip install --upgrade pip \
 && apk --no-cache add --virtual .build-deps gcc libffi-dev python3-dev linux-headers musl-dev openssl-dev \
 && pip install gsutil \
 && apk del .build-deps
COPY run-test /usr/local/bin
COPY config.gsutil.pl /usr/local/bin/config.pl
RUN chmod +x /usr/local/bin/run-test /usr/local/bin/config.pl
ENTRYPOINT [ "perl", "/usr/local/bin/run-test" ]
